saving_throws = {
    "fortitude", "reflex", "will"
}
skills = {
    "acrobatics": "dexterity",
    "arcana": "intelligence",
    "athletics": "strength",
    "crafting": "intelligence",
    "deception": "charisma",
    "diplomacy": "charisma",
    "intimidation": "charisma",
    "medicine": "wisdom",
    "nature": "wisdom",
    "occultism": "intelligence",
    "performance": "charisma",
    "religion": "wisdom",
    "society": "intelligence",
    "stealth": "dexterity",
    "survival": "wisdom",
    "thievery": "dexterity",
}
actions_type = {
    "free": 0,
    "reaction": -1,
}
dc_by_level = {
    -2: "DC 12",
    -1: "DC 13",
    0: "DC 14",
    1: "DC 15",
    2: "DC 16",
    3: "DC 18",
    4: "DC 19",
    5: "DC 20",
    6: "DC 22",
    7: "DC 23",
    8: "DC 24",
    9: "DC 26",
    10: "DC 27",
    11: "DC 28",
    12: "DC 30",
    13: "DC 31",
    14: "DC 32",
    15: "DC 34",
    16: "DC 35",
    17: "DC 36",
    18: "DC 38",
    19: "DC 39",
    20: "DC 40",
    21: "DC 42",
    22: "DC 44",
    23: "DC 46",
    24: "DC 48",
    25: "DC 50",
}
skill_by_tradition = {
    "Aberration": "Occultism",
    "Animal": "Nature",
    "Astral": "Occultism",
    "Beast": "Arcana or Nature",
    "Celestial": "Religion",
    "Construct": "Arcana or Crafting",
    "Dragon": "Arcana",
    "Dream": "Occultism",
    "Elemental": "Arcana or Nature",
    "Ethereal": "Occultism",
    "Fey": "Nature",
    "Fiend": "Religion",
    "Fungus": "Nature",
    "Humanoid": "Society",
    "Monitor": "Religion",
    "Ooze": "Occultism",
    "Plant": "Nature",
    "Shade": "Religion",
    "Spirit": "Occultism",
    "Time": "Occultism",
    "Undead": "Religion",
}
excluded_abilities = {
    "tremorsense",
    "telepathy",
    "status to all saves",
    "status to will saves",
    "status to reflex saves",
    "status to fortitude saves",
    "constant spell",
    "darkvision",
}